version: "3.3"

services:
  resolve-pip-deps:
    image: robsoko-api:dev
    volumes:
      - ./:/home/appuser/workspace
    working_dir: /home/appuser/workspace
    networks:
      - api-network
    command: pip-compile -r ./requirements.in

  pycharm-dev:
    image: robsoko-api:dev
    ports:
      - "8000:8000"
    volumes:
      - /home/rob/code/api:/home/appuser/run
    working_dir: /home/appuser/run
    command:
      python /home/appuser/run/run_api_dev.py

  api:
    image: robsoko-api:latest
    ports:
      - 80:80

networks:
  api-network:
    driver: bridge
    ipam:
      driver: default
