FROM robsoko-api:dev

# Since the service writes to its own home directory, we must grant ownership of the data we're about to copy in
# Mounting a drive during dev implicitly achieves this, which is why we only do this operation in the deployed version
USER root
COPY ./ /home/appuser
RUN chown -R appuser /home/appuser
USER appuser

CMD ["sh", "-c", "gunicorn --workers 1 --timeout 3600 --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 api.server:app"]
