FROM python:3.9-slim

RUN apt-get update
RUN apt-get install -y \
    gcc \
    curl \
    python3-dev \
    python3-pip \
    libxml2-dev \
    libxslt1-dev \
    zlib1g-dev \
    g++

# Don't run rest as root
RUN useradd -ms /bin/bash appuser
USER appuser

ENV PATH=$PATH:/home/appuser/.local/bin
ENV PYTHONPATH="/home/appuser"

RUN mkdir /home/appuser/install
WORKDIR /home/appuser/install
COPY ./requirements.txt ./
RUN pip install --user --upgrade pip
RUN pip install --user pip-tools
RUN pip install --user -r ./requirements.txt

RUN mkdir /home/appuser/data


WORKDIR /home/appuser
