version: "3.3"

services:
  resolve-pip-deps:
    image: robsoko-api:dev
    volumes:
      - ./:/home/appuser/workspace
    working_dir: /home/appuser/workspace
    networks:
      - api-network
    command: pip-compile -r ./requirements.in

  pycharm-dev:
    image: robsoko-api:dev
    volumes:
      # Note: There appears to be an issue with the WSL / Docker-compose / PyCharm trio not quite working
      - /home/rob/data/:/home/appuser/data
#    ports:
#      - 8000:8000
    env_file:
      - .env

  pytest-dev:
    image: robsoko-api:dev
    volumes:
      # Note: There appears to be an issue with the WSL / Docker-compose / PyCharm trio not quite working
      - /home/rob/data/:/home/appuser/data
    env_file:
      - .env

  api-dev:
    image: robsoko-api:dev
    ports:
      - 8000:8000
    working_dir: /home/appuser/run
    volumes:
    - ./:/home/appuser/run
    command: python run_api_dev.py
    env_file:
      - .env

  api-gunicorn:
    image: robsoko-api:latest
    ports:
      - 8080:8080
    env_file:
      - .env

networks:
  api-network:
    driver: bridge
    ipam:
      driver: default
