FROM robsoko-api:dev

USER root
COPY ./ /home/appuser
RUN chown -R appuser /home/appuser
USER appuser

CMD ["sh", "-c", "gunicorn --workers 4 --timeout 3600 --worker-class uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 api.server:app"]
