version: "3.3"

services:
  resolve-pip-deps:
    image: fir-api:dev
    volumes:
      - ./:/home/appuser/workspace
    working_dir: /home/appuser/workspace
    networks:
      - api-network
    command: pip-compile -r ./requirements.in

  pycharm-dev:
    image: fir-api:dev
    ports:
      - 8000:8000
    env_file:
      - local-dev.env

  pytest-dev:
    image: fir-api:dev
    env_file:
      - local-dev.env

  upload-creds-to-bucket:
    image: fir-api:dev
    working_dir: /home/appuser/run
    volumes:
    - ./:/home/appuser/run
    command: python run_upload_creds_to_gcs.py
    env_file:
      - local-dev.env

  api-dev:
    image: fir-api:dev
    ports:
      - 8000:8000
    working_dir: /home/appuser/run
    volumes:
    - ./:/home/appuser/run
    command: python run_api_dev.py
    env_file:
      - local-dev.env

  api-gunicorn:
    image: fir-api:latest
    ports:
      - 8080:8080
    env_file:
      - local-dev.env

networks:
  api-network:
    driver: bridge
    ipam:
      driver: default
