version: "3.3"

services:
  pytest:
    image: gcr.io/fir-sandbox-326008/robsoko-api:dev
    env_file:
      - ci.env

networks:
  api-ci-network:
    driver: bridge
    ipam:
      driver: default
